### ISSUE TITLE
Dispatch workflow is failing

### ISSUE THREAD

**Issue by sbesson** [ome/ome-zarr-py#126]
See https://github.com/ome/ome-zarr-py/actions/workflows/dispatch.yml e.g. https://github.com/ome/ome-zarr-py/runs/4140227357?check_suite_focus=true

```
Run peter-evans/repository-dispatch@v1
Error: Parameter token or opts.auth is required
```

**Comment by jburel** [comment]
The secrets are not accessible when merging the PR into main/master
I have now changed the job to run on merge to master 
https://github.com/ome/ome-zarr-py/runs/4142265825?check_suite_focus=true

**Comment by sbesson** [comment]
Now successfully working - see https://github.com/ome/ome_zarr_test_suite/runs/4787513802?check_suite_focus=true
