### ISSUE TITLE
Improving signal-to-noise with snoopycrimecop 

### ISSUE THREAD

**Issue by jakirkham** [ome/ome-zarr-py#137]
Like following this repo to keep track of issues that may be coming up or use cases users present. However it seems recently a bot ( snoopycrimecop ) was added here, which is generating a fair number of issues (and associated notifications). Am wondering if there is a way to adjust how the bot behaves to allow for easier tracking of user issues. As one option, would it be possible to have the bot comment in only one dedicated issue? Or is there some other way that it might be configured that would have a similar result?

**Comment by jburel** [comment]
Sorry for the noise, I am currently improving the workflow leading to a number of issues being created.
Hopefully that should be improved shortly.

**Comment by jakirkham** [comment]
No worries. These things happen from time to time (especially when trying out new automation workflows). Thanks both for the quick reply and looking into this issue 🙂

**Comment by jburel** [comment]
The logic is now fixed.
The workflow is as follows: 
* Each time a commit is merged to master in this repository, a ``repository dispatch`` event will  be sent to https://github.com/ome/ome_zarr_test_suite. The test suite repository contains tests for several "zarr" related repositories/
* The tests related to ome-zarr-py will be run.
* If the tests failed, an issue in this repository will be created indicating the sha and a link to the job failure.
