### ISSUE TITLE
HCS stitching of Wells to Plate broken for data less than 5D

### ISSUE THREAD

**Issue by will-moore** [ome/ome-zarr-py#145]
The concatenation of Wells into a Plate assumes 5D images.
This is not always the case with v0.3, since this version supports 2D -> 5D

e.g. https://uk1s3.embassy.ebi.ac.uk/0.3_samples/7751.zarr 
See this [plate in vizarr](https://hms-dbmi.github.io/vizarr/?source=https://uk1s3.embassy.ebi.ac.uk/0.3_samples/7751.zarr)
cc @sbesson

**Comment by sbesson** [comment]
Transferred the issue from `napari-ome-zarr` as running  `ome_zarr info` on the plates reveals the same issue
