### ISSUE TITLE
Rename parameter: fmt -> format

### ISSUE THREAD

**Issue by jburel** [ome/ome-zarr-py#156]
The name of fields in the methods in the library are mostly explicit e.g. ``columns``, ``wells``.
``format`` should be used instead of ``fmt``. See https://github.com/ome/ome-zarr-py/pull/153#discussion_r782856448

**Comment by will-moore** [comment]
I think that `format` is avoided as a variable name since it would overwrite the built-in `format()` function:
https://docs.python.org/3/library/functions.html#format

**Comment by dstansby** [comment]
Probably worth closing this?
