### ISSUE TITLE
add compressor to write_image

### ISSUE THREAD

**Issue by satra** [ome/ome-zarr-py#160]
i couldn't see an exposed interface for compressing the chunks. is this intentional? if not, i will send a  PR to alter `write_image` to take a compressor keyword and passing it on to zarr array creation.

**Comment by will-moore** [comment]
Hi @satra - It's certainly not intentional to restrict that option.
Please feel free to open a PR to add compressor support.
 Thanks!

**Comment by satra** [comment]
@will-moore - i'll work on #161 then.
