### ISSUE TITLE
Documentation & parsing ome-zarr with original zarr package

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [ome/ome-zarr-py#163]
Dear all,

Could you tell me if there is any documentation available for ome-zarr-py?
Also, is it possible to straightforwardly parse zarr arrays contained in ome-zarr fileset using original zarr Python package (https://github.com/zarr-developers/zarr-python)?

Best regards,
Aliaksei

**Comment by sbesson** [comment]
HI @aliaksei-chareshneu, the README contains some usage instructions but we started the discussion in https://github.com/ome/ome-zarr-py/pull/121 around generating some readthedocs documentation. It would be useful to know what would be useful for you.

On the second question, absolutely, OME-Zarr filesets are effectively Zarr hierarchies and arrays in a structure that is defined by the [OME-NGFF](ngff.openmicroscopy.org/latest/) specification with conventions and metadata defined at the appropriate group levels. It should be absolutely possible to open these filesets using the Zarr python package which is a dependency of this package.

**Comment by will-moore** [comment]
There is a PR in progress to add a small code sample for writing OME zarr: https://github.com/ome/ome-zarr-py/pull/121

**Comment by BioinfoTongLI** [comment]
+1 on this thread.
I've found some codes for the parsing in the `tests`. Tho, as far as I can tell, ome_zarr currently is not loading the metadata at all (xml file in [zarr_root]/OME/METADATA.ome.xml). It seems to be the case in the napari-ome-zarr plugin as well. 
Is there any plans on linking the md and binary data more tightly, like via one single loading?
Best,
Tong

**Comment by sbesson** [comment]
@BioinfoTongLI at the moment the XML file in `[zarr_root]/OME/METADATA.ome.xml` is a  specific to the implementation in https://github.com/glencoesoftware/bioformats2raw and is primarily driven by compatibility with the follow-up `raw2ometiff` component of the pipeline. Under the top-level Zarr group, each Zarr group containing an image (`0`, `1`...) should be a valid OME-NGFF multiscales image (currently at version 0.2). The `OME` group containing the OME-XML metadata is not formally defined in the OME-NGFF specification yet so it should not be expected that `ome-zarr-py` can natively understand this layout at the moment. 

We discussed this aspect as part of yesterday's NGFF community call and handling the relationship between images and metadata and making a formal specification proposal is definitely on the immediate roadmap of the OME team.

**Comment by dstansby** [comment]
Given https://ome-zarr.readthedocs.io/en/stable/ exists for documentation, I think this can be closed?
