### ISSUE TITLE
Store axes as `_ARRAY_DIMENSIONS`

### ISSUE THREAD

**Issue by sbesson** [ome/ome-zarr-py#166]
Noticed while reviewing https://github.com/glencoesoftware/bioformats2raw/pull/121, the `ome_zarr.writer` API currently does not store the axes metadata as `_ARRAY_DIMENSIONS` under the `.zattrs` of each resolution array.

Since this is a requirement of the spec,introduced in 0.3 - see https://ngff.openmicroscopy.org/0.3/#multiscale-md, the relevant writer APIs should be updated before releasing 0.3.0.

**Comment by joshmoore** [comment]
:+1: but if I remember correctly the status of my testing showed that attempting to access the zgroup with xarray led to an exception. The workaround suggested by @aurghs and @alexamici was to use differently named axes per resolution level > 0.

see: https://github.com/zarr-developers/zarr-specs/issues/125
cc: @constantinpape

**Comment by sbesson** [comment]
Cheers, I wasn't aware of the limitation and that's definitely something that should be tested with the writer addition.

If some the axes names needs to be resolution-awre in the `_ARRAY_DIMENSIONS` (I could imagine simply suffixing them with the resolution index i.e.`x_1,` `x_2`, I suspect this is something we should formalize in the specification sooner rather than later given that this is marked as a requirement.

**Comment by constantinpape** [comment]
> +1 but if I remember correctly the status of my testing showed that attempting to access the zgroup with xarray led to an exception. The workaround suggested by @aurghs and @alexamici was to use differently named axes per resolution level > 0.

Is there a concrete issue for this? I couldn't find any mention of this problem in the one you linked (https://github.com/zarr-developers/zarr-specs/issues/125).

**Comment by will-moore** [comment]
I'm still not entirely clear from the NGFF spec and the xarray page whether `_ARRAY_DIMENSIONS` goes on the top `.zattrs` alongside `"multiscales"` (and does xarray know how to find the `arrays`?) or does it go in the `.zarray`? It's not in any of the sample JSON on the spec page.
Ah - re-reading... does it go in a `.zattrs` (which we don't create currently) alongside the `.zarray`?

**Comment by sbesson** [comment]
>  Ah - re-reading... does it go in a .zattrs (which we don't create currently) alongside the .zarray?

Yes exactly, this metadata is expected to be defined in the array attributes

**Comment by joshmoore** [comment]
> Is there a concrete issue for this?

Apologies, @constantinpape, no. This happened to date on the Zarr side with setting up the funding and getting B-Open up to speed.

**Comment by sbesson** [comment]
I was able to reproduce the error with the following local changes

```diff
(base) sbesson@ls30630:ome-zarr-py (xarray_investigation) $ git diff  --cached
diff --git a/.isort.cfg b/.isort.cfg
index b3d36cb..367ece7 100644
--- a/.isort.cfg
+++ b/.isort.cfg
@@ -1,5 +1,5 @@
 [settings]
-known_third_party = dask,numpy,pytest,scipy,setuptools,skimage,zarr
+known_third_party = dask,numpy,pytest,scipy,setuptools,skimage,xarray,zarr
 multi_line_output = 3
 include_trailing_comma = True
 force_grid_wrap = 0
diff --git a/ome_zarr/writer.py b/ome_zarr/writer.py
index 83bbe6d..497ed32 100644
--- a/ome_zarr/writer.py
+++ b/ome_zarr/writer.py
@@ -206,8 +206,9 @@ def write_multiscale(
     datasets: List[dict] = []
     for path, data in enumerate(pyramid):
         # TODO: chunks here could be different per layer
-        group.create_dataset(str(path), data=data, chunks=chunks)
+        dataset = group.create_dataset(str(path), data=data, chunks=chunks)
         datasets.append({"path": str(path)})
+        dataset.attrs["_ARRAY_DIMENSIONS"] = [x["name"] for x in axes]
 
     if coordinate_transformations is None:
         shapes = [data.shape for data in pyramid]
diff --git a/requirements/requirements-test.txt b/requirements/requirements-test.txt
index 9cf8484..cc5774c 100644
--- a/requirements/requirements-test.txt
+++ b/requirements/requirements-test.txt
@@ -1,3 +1,4 @@
 pytest
 pytest-cov
 codecov
+xarray
diff --git a/tests/test_xarray.py b/tests/test_xarray.py
new file mode 100644
index 0000000..187681f
--- /dev/null
+++ b/tests/test_xarray.py
@@ -0,0 +1,14 @@
+import pytest
+import xarray
+
+from ome_zarr.data import create_zarr
+
+
+class TestXarray:
+    @pytest.fixture(autouse=True)
+    def initdir(self, tmpdir):
+        self.path = tmpdir.mkdir("data")
+        create_zarr(str(self.path))
+
+    def test_open_zarr(self):
+        xarray.open_zarr(str(self.path))
```

Running `tox -e py38 tests/test_xarray.py` fails with `ValueError: conflicting sizes for dimension 'y': length 812 on '1' and length 1624 on {'y': '0', 'x': '0'}`

The workaround mentioned in https://github.com/ome/ome-zarr-py/issues/166#issuecomment-1029793391 i.e. suffixing the axes name using the resolution level is sufficient to let this simple test pass:

```diff
diff --git a/ome_zarr/writer.py b/ome_zarr/writer.py
index 497ed32..c5438a3 100644
--- a/ome_zarr/writer.py
+++ b/ome_zarr/writer.py
@@ -208,7 +208,7 @@ def write_multiscale(
         # TODO: chunks here could be different per layer
         dataset = group.create_dataset(str(path), data=data, chunks=chunks)
         datasets.append({"path": str(path)})
-        dataset.attrs["_ARRAY_DIMENSIONS"] = [x["name"] for x in axes]
+        dataset.attrs["_ARRAY_DIMENSIONS"] = ["%s_%s" %(x["name"], path) for x in axes]
 
     if coordinate_transformations is None:
         shapes = [data.shape for data in pyramid]
```

Discussing briefly with @joshmoore, I feel like we need to make a decision before we release OME-NGFF 0.4 and implement the feature across libraries. I can see three viable options:

1. keep the specification as it currently stand i.e. https://github.com/ome/ngff/blob/12acbb69dba91da09f162eb806c59161601dc1c0/latest/index.bs#L267-L269, implement this feature across the board and file this as an xarray bug which needs to be upstream to support this metadata-style
2. update the specify to mandate an alternate form like the one proposed above for storing xarray-compatible metadata in multiscales OME-NGFF datasets and update the implementations accordingly
3. keep investigating options and solutions but reduce the the xarray-compatibility requirement from MUST to either SHOULD or even MAY level.

/cc @aurghs  @alexamici  @constantinpape happy to discuss on the image.sc zulip or get on a call if that would help resolving this outstanding issue.

**Comment by constantinpape** [comment]
@joshmoore @sbesson I am still missing some context here about what the actual problem is. Could you please give me a few line TLDR?
