### ISSUE TITLE
writing images with arbitrary channel position 

### ISSUE THREAD

**Issue by maweigert** [ome/ome-zarr-py#191]
Hi, 

I was wondering whether arbitrary channel positions are supported (e.g. writing rgb images with channel last)? 

Currently the following results in an error:

```python 

import numpy as np
import zarr
from ome_zarr.io import parse_url
from ome_zarr.writer import write_image

data = np.random.uniform(0,1,(100,100,3))
root = zarr.group(store=parse_url("foo.zarr", mode="w").store)
write_image(image=data, group=root, axes="yxc")

```

```
ValueError: 'space' axes must come after 'channel'
```

**Comment by constantinpape** [comment]
> I was wondering whether arbitrary channel positions are supported (e.g. writing rgb images with channel last)?

This is currently not supported by the NGFF spec. Channels must come before spatial axes (and after time).
We have chosen to have this restriction for now to keep implementing the spec manageable. For general discussions about this you can make an issue in the ngff spec: https://github.com/ome/ngff
(The relevant text: https://github.com/ome/ngff/blob/main/latest/index.bs#L276)
