### ISSUE TITLE
question: transition from hdf5 to ome-zarr-py

### ISSUE THREAD

**Issue by kasasxav** [ome/ome-zarr-py#226]
Hi!

I am trying to see if I could implement ome-zarr-py where now we use HDF5. There are some operations though that I don't know how to do, and wanted to ask if the functionality is there and I'm not finding it? I know in Zarr you can do those things, it seems at least.

So usually what we do is to create a dataset in hdf5, and then return the object dataset. Then we write the image in chunks, something like this:

`dataset.resize(n + it, axis=0)
 dataset[it:it + n, :, :] = newFrames`

And then close the file. For now I can only find write_image in the API and in the Writer class, is there a way I could do this? I checked the zarr documentation and it seems that this should be possible.

**Comment by will-moore** [comment]
Hi @kasasxav,

Given the current API, you can use `ome-zarr-py` to write the metadata, but write the data yourself using the underlying `zarr` library.

You can see how this is happening in https://github.com/ome/ome-zarr-py/blob/13165f410c209cc4e50e81b9ac0ce850c367a9b5/ome_zarr/writer.py#L176 so you can do something similar, replacing the `group.create_dataset()` with your own method for writing the zarr.

We are actually doing this in `omero-cli-zarr` where we're exporting from OMERO, retrieving a plane at a time from the server and writing to disk, then using `ome-zarr-py` to write the metadata:

Something similar to `dataset[it:it + n, :, :] = newFrames` is happening at https://github.com/ome/omero-cli-zarr/blob/a7b9e4f73e8ed034c154472a2e10b96f3755e1ca/src/omero_zarr/raw_pixels.py#L182, except writing a single plane at a time.

 Hope that's useful?

  Will

**Comment by kasasxav** [comment]
Thank you very much ! Very useful indeed, I will do as you suggest.

I have one more question, in the hdf5 I usually write metadata that is quite specific to our technique (like laser pulse durations and powers, stage positions etc), is there a specific way to do this with ome-zarr? I have been trying to read into the papers but I didn't manage to find it. In hdf5 we add it as datset.attrs

**Comment by kasasxav** [comment]
Alright, thank you again! I close for now and will write there when I'm a bit more into it :)

**Comment by kasasxav** [comment]
Sorry again, last question :P What is the best way to do it? Changing it in ome-zarr-py and having my "own version" of it, or copying the code from write_multiscale into my file and then use  write_multiscales_metadata from the original ome-zarr-py?

**Comment by will-moore** [comment]
I would go for option 2.

If you can think of a nice way to add to the `ome-zarr-py` api to allow you to do what you want (without breaking existing API), then please consider opening a pull request. But don't fork you "own version" of it or you'll have more work to do to keep up to date.
