### ISSUE TITLE
Provide a remote/s3 example in the docs

### ISSUE THREAD

**Issue by joshmoore** [ome/ome-zarr-py#239]
See https://forum.image.sc/t/cli-programmatic-browsing-of-ome-zarr-hierarchies-on-idr/75907/9

If an example exists, perhaps it's just a matter of the findability.

**Comment by pgarrison** [comment]
There is one example here: https://ome-zarr.readthedocs.io/en/stable/python.html#reading-ome-ngff-images

**Comment by joshmoore** [comment]
Thanks, @pgarrison
