### ISSUE TITLE
Don't hardcode channel axis, or any other metadata really, if array is not OME?

### ISSUE THREAD

**Issue by jni** [ome/ome-zarr-py#25]
Hardcoding the dimensions to TCZYX and channel_axis=1 makes sense when the array can be ascertained to be an OME array, but it seems pretty bold to do it on any random array, of any shape, too. Example:

```python
import numpy as np
import zarr

fout = zarr.open('demo-zarr-3d.zarr', mode='w', shape=(5, 10, 10), dtype=np.float32) 
fout[:] = np.random.random((5, 10, 10)) 
```

If I then do:

```python
napari demo-zarr-3d.zarr
```

in the command line, having installed `ome-zarr`, I get:

![napari-zarr](https://user-images.githubusercontent.com/492549/82426074-fe212b00-9a4c-11ea-9bd2-ff6f0b2cec78.png)

**Comment by jni** [comment]
These are the relevant lines of code:

https://github.com/ome/ome-zarr-py/blob/1ae04f04b078b9016535373e78ea232f54d2d253/ome_zarr.py#L123-L125

**Comment by joshmoore** [comment]
All makes sense. (Cross-reading with zulip) I'm wondering if perhaps this package should provide _2_ plugins based on `is_ome_zarr`.

**Comment by jni** [comment]
I just think a good start would be removing that channel axis thing. =)

**Comment by joshmoore** [comment]
cc: @will-moore

**Comment by will-moore** [comment]
Yes, I think if it's not an `ome-zarr` file then we don't need to use ```{'channel_axis': 1}```.
I guess that is effectively providing 2 plugins.

Do we want to handle non-```ome-zarr``` data at all? If we return nothing then we give other plugins a chance to handle it. But will most users likely have a plugin that can handle that already?

**Comment by jni** [comment]
Our built-in plugin uses `da.from_zarr(path)` if it gets a zarr file. If you don't want to do anything else, then you might as well leave it to us! But if you do have suggestions for doing fancier things, I'd stick them in here. =) For example, I don't know what `da.from_zarr` does if a file contains a group rather than a single array?

**Comment by jni** [comment]
(as in the case of multiscale)

**Comment by jni** [comment]
@joshmoore care to make a new release including this? Feel free to add me to the PyPI maintainers if you want to offload some work! 😁 I'm jni there also. (Or let me know if there's anything else you want done before release but don't have time right now.)

**Comment by joshmoore** [comment]
All good ideas, but for a Sunday, pushing a tag was the easiest. `v0.0.8` cut and travis was kind enough to release: https://pypi.org/project/ome-zarr/0.0.8/
