### ISSUE TITLE
write_multiscale defaults to no compression

### ISSUE THREAD

**Issue by jni** [ome/ome-zarr-py#250]
Is this intentional?

I'm on main/master.

```python
import numpy as np
import dask.array as da
import zarr
from ome_zarr.io import parse_url
from ome_zarr.writer import write_multiscale
from pathlib import Path
from tempfile import TemporaryDirectory

with TemporaryDirectory(suffix='.ome.zarr') as path:
    arr = da.zeros(  # 100MB array, 4MB chunks, trivially compressible
            (25, 50, 200, 400), dtype=np.uint8, chunks=(1, 50, 200, 400)
            )
    store = parse_url(path, mode='w').store
    root = zarr.group(store=store)
    write_multiscale([arr], group=root, axes='tzyx')

    # chunk size on disk in MB
    print((Path(path) / '0/0/0/0/0').stat().st_size / 1e6)
```

Prints: 4.0

Bonus points if anyone can answer my Q on [Twitter](https://twitter.com/jnuneziglesias/status/1627434802461954048) or [Mastodon](https://fosstodon.org/@jni/109893759738828229)! 😂

**Comment by will-moore** [comment]
Thanks for the feedback.
We're not deliberately avoiding compression here, so I guess the answer is "no".

**Comment by jni** [comment]
Ok, will investigate! It was surprising to me because zarr-python defaults to Blosc, so I guess we can try to find a way to not override that default.
