### ISSUE TITLE
Example invocations not working due to SSL issues (on some systems)

### ISSUE THREAD

**Issue by ngladitz** [ome/ome-zarr-py#26]
Frustratingly none of the example invocations seemed to be working for me.

E.g. `ome_zarr info https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/` just gave me the following diagnostics:
```
WARNING:ome_zarr:unreachable: https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/.zarray
WARNING:ome_zarr:unreachable: https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/.zgroup
not an ome-zarr: https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/
```

Digging further "unreachable" was apparently due to the following exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 352, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1108)
```

And this seems to be connected to Debian (in my case Ubuntu) where the default security level for TLS connections was apparently raised from level 1 to level 2:
- https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_get_security_level.html
- http://changelogs.ubuntu.com/changelogs/pool/main/o/openssl/openssl_1.1.1f-1ubuntu1/changelog

One sub-optimal work around seems to be manually overriding the security level.

Beyond documenting this so others who run into the same issue might have to do less digging ...
it might be nice to forward the underlying error to the user (I found "unreachable" somewhat misleading in this case).

Assuming the issue partly lies with the server where these images are hosted ...
could someone here notify them of the issue or would know who to notify?

**Comment by joshmoore** [comment]
Issue closed since the logging issue was handled. If any more help is needed, feel free to re-open or create a new issue.
