### ISSUE TITLE
Update ome-zarr-py to display masks

### ISSUE THREAD

**Issue by joshmoore** [ome/ome-zarr-py#29]
Since napari reader can return a layer type, See https://napari.org/docs/plugins/hook_specifications.html#napari.plugins.hook_specifications.napari_get_reader
we if this plugin can recognise a mask then it can be handled as a labels layer by napari.

And this plugin should also handle any conversion of dimensions needed. See https://github.com/ome/omero-cli-zarr/pull/11#issuecomment-653414971

**Comment by will-moore** [comment]
Going to have a go at this.
Simplest case:
 - You have local `123.zarr/` which contains `masks/`.
 - In this case, `napari 123.zarr` would open the image AND the masks.

With a plugin you don't get to choose any arguments, so you can't choose whether to load masks, but if you have all the data in hand then it you might as well load it.

Another potential use-case:
 - You want to open the mask on it's own (e.g. you may not have the image data locally)
 - E.g. `napari 123.zarr/masks/`

If data is remote, this is harder:
 - e.g. `napari 'https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/' ` Is it possible to test for the existence of masks, or just to try and load them anyway?
 - Although you don't want to load unnecessary data if remote, you won't load too much up front and you can always turn masks off to avoid loading more.

**Comment by joshmoore** [comment]
Ha. I was just pondering about [`LayerData`](https://napari.org/docs/plugins/for_plugin_developers.html#plugins-hook-spec). Leaving this to you then, and I'll look at a next version of omero-cli-zarr.

> * Is it possible to test for the existence of masks, or just to try and load them anyway?

It's worse than that. Not possible currently to even find them. This will take registering metadata in the `masks/.zattrs`

**Comment by will-moore** [comment]
I guess another possibility is that you have the pixel data remote and the mask data local. That's what I had in https://github.com/ome/omero-cli-zarr/pull/11#issuecomment-652531164 (took too long to download the pixel data, but I had created the masks locally). 

I that case you'd want to do:

`$ napari 'https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr/'`
or
`$ omero napari view Image:6001240`

Then in the napari console:
```
viewer.open('local/path/to/6001240.zarr/masks')
```
So the plugin would behave as in the 2nd use-case above. It just needs to recognise masks vv images.

**Comment by joshmoore** [comment]
Loading separately is certainly always an option. For the moment, I'd probably try to either get the mask layer automatically added (though perhaps deactivated by default?) or have a button to look them up, preferably from the original fileset but from another fileset if need be.

see: https://github.com/ome/omero-cli-zarr/pull/12
