### ISSUE TITLE
Releases on GitHub out of date

### ISSUE THREAD

**Issue by dstansby** [ome/ome-zarr-py#325]
At https://github.com/ome/ome-zarr-py/releases the latest release is version 0.2.0, but that was a long time ago!

<img width="251" alt="Screenshot 2023-11-20 at 12 00 40" src="https://github.com/ome/ome-zarr-py/assets/6197628/722beb29-b87d-4386-8955-71ed279ac312">

I'd suggest either deleting the existing old releases, or to start creating releases for new versions so it doesn't look like the last release was over two years ago.

**Comment by joshmoore** [comment]
Thanks for the heads up, @dstansby. Now updated:

![image](https://github.com/ome/ome-zarr-py/assets/88113/eae7a220-c9d6-456d-ab5d-e415ad0ae681)
