### ISSUE TITLE
Reading multiscales metadata

### ISSUE THREAD

**Issue by k-dominik** [ome/ome-zarr-py#345]
Dear ome-zarr-py developers,

apologies in advance if I missed something very obvious.

we're looking into adding support for ngff to [ilastik](https://github.com/ilastik/ilastik) via `ome-zarr-py`. I have some trouble understanding how metadata is supposed to be read.
I'll take one example from [idr/ome-ngff-samples](https://idr.github.io/ome-ngff-samples/), in particular `https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0048A/9846152.zarr/`.

When I read the data with minimal effort I have something like

```python
from ome_zarr.io import parse_url
from ome_zarr.reader import Reader

url = "https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0048A/9846152.zarr"
reader = Reader(parse_url(url))
nodes = list(reader())
image_node = nodes[0]
```

then, when I want to see the metadata, i could use `image_node.metadata` which will produce the following:

<details><summary>`image_node.metadata` output</summary>

```python
{'axes': [{'name': 'c', 'type': 'channel'},
          {'name': 'z', 'type': 'space'},
          {'name': 'y', 'type': 'space'},
          {'name': 'x', 'type': 'space'}],
 'colormap': [[[0, 0, 0], [1.0, 0.0, 0.0]],
              [[0, 0, 0], [0.0, 1.0, 0.0]],
              [[0, 0, 0], [0.0, 0.0, 1.0]]],
 'contrast_limits': [[0.0, 25000.0], [0.0, 25000.0], [0.0, 25000.0]],
 'coordinateTransformations': [[{'scale': [1.0, 1.0, 1.0, 1.0],
                                 'type': 'scale'}],
                               [{'scale': [1.0, 1.0, 2.0, 2.0],
                                 'type': 'scale'}],
                               [{'scale': [1.0, 1.0, 4.0, 4.0],
                                 'type': 'scale'}],
                               [{'scale': [1.0, 1.0, 8.0, 8.0],
                                 'type': 'scale'}],
                               [{'scale': [1.0, 1.0, 16.0, 16.0],
                                 'type': 'scale'}],
                               [{'scale': [1.0, 1.0, 32.0, 32.0],
                                 'type': 'scale'}],
                               [{'scale': [1.0, 1.0, 64.0, 64.0],
                                 'type': 'scale'}],
                               [{'scale': [1.0, 1.0, 128.0, 128.0],
                                 'type': 'scale'}],
                               [{'scale': [1.0, 1.0, 256.0, 256.0],
                                 'type': 'scale'}]],
 'name': ['0', '1', '2'],
 'visible': [True, True, True]}
```
</details>

I'm trying to relate this to [ngff 0.4 specifications](https://ngff.openmicroscopy.org/0.4/#multiscale-md). There I would expect at least a `multiscale` key. `image_node.specs[0].datasets` let's me query for the keys of the resolution levels, but that's not very useful to me. Or what attribute should the metadata be read from?

In the data above - is this already the transformations merged from the common `coordinateTransformations` key and the respective `coordinateTransformations` that could be in `multiscales`?

Also would it be possible to find out which version of spec one is looking at?

Thank you 🙌 

_ome-zarr version: 0.8.0_

**Comment by bugraoezdemir** [comment]
Hi @k-dominik , 

As we privately discussed, the `image_node.metadata` does not provide the metadata according to the json structure in the ngff specs. To obtain the metadata according in the correct structure, you can do:

```
url  =  "https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0048A/9846152.zarr"
reader   = Reader(parse_url(url))
metadata = reader.zarr.root_attrs
```
The `metadata`  follows the ngff specs.

**Comment by will-moore** [comment]
@bugraoezdemir Thanks for that.
Yes the `image_node.metadata` is in a form used by `napari`. Originally the `napari-ome-zarr` plugin and this repo were all one repo, so we could just pass that metadata directly to `napari`.
Now, `napari-ome-zarr` consumes the `image_node.metadata` but it is still in the same format. Apologies for the confusion.

I guess we could consider moving the formatting of this metadata into `napari-ome-zarr` and instead expose the NGFF metadata as you were expecting.

**Comment by k-dominik** [comment]
Thank you @bugraoezdemir and @will-moore. I think I can work with that now!


> I guess we could consider moving the formatting of this metadata into `napari-ome-zarr` and instead expose the NGFF metadata as you were expecting.

Not sure if removing it here would be necessary. I'd just expect the primary way to query for metadata would give me something according to spec :).

In the meantime It would be nice to document how to access the ome-zarr metadata for consumers other than napari.

**Comment by joshmoore** [comment]
Not to disagree with the need for improvements in ome-zarr-py, @k-dominik, but you might also be interested in https://github.com/JaneliaSciComp/pydantic-ome-ngff (cc: @d-v-b) and/or https://github.com/thewtex/ngff-zarr (cc: @thewtex)

**Comment by k-dominik** [comment]
Thank you @joshmoore,

for some reason I thought `ome-zarr-py` would be the most developed of all libraries and I have to say that now knowing where to access what, it also does the job for me...
