### ISSUE TITLE
Package-level members

### ISSUE THREAD

**Issue by vreuter** [ome/ome-zarr-py#368]
Hello, would you consider making some types, like`ZarrLocation`, available at the package level, to facilitate e.g. `from ome_zarr import ZarrLocation`, rather than needing to specify that this is from `io`? It would have at least these benefits...

a) make it easier to get started with using this as a library after quickly scanning the documentation and not yet internalising where each desired piece of functionality is implemented, and without needing to do as much object inspection in a REPL.
b) make the library more robust for users against future potential refactors and changes in the placement of implementations / organisation of the library, with less lift on the dev side needed to support backward compatibility

**Comment by joshmoore** [comment]
Hi @vreuter, in general, sure. Very open to suggestions. That beings said, it might be, especially as we move towards Zarr v3, that we try to hide, deprecate or remove much of the `io` package which was necessary with Zarr v2. What would you think about reviewing the situation once that work has taken place?

**Comment by vreuter** [comment]
> That beings said, it might be, especially as we move towards Zarr v3, that we try to hide, deprecate or remove much of the `io` package which was necessary with Zarr v2. 

OK, understood

> What would you think about reviewing the situation once that work has taken place?

Yes, sounds good :)

TY @joshmoore I'm going to close this for now to reduce noise in the issues, hope that's OK and obviously feel free to reopen if this ticket's wanted as a reminder
