### ISSUE TITLE
Installation issue with ome-zarr-py

### ISSUE THREAD

**Issue by jrevote** [ome/ome-zarr-py#40]
Running:

pip install ome-zarr

Produces build errors:

   c-blosc/internal-complibs/zstd-1.4.1/decompress/zstd_decompress.c:92:21: error: use of undeclared identifier 'ZSTD_FRAMEHEADERSIZE_PREFIX'
                        ZSTD_FRAMEHEADERSIZE_PREFIX - ZSTD_FRAMEIDSIZE :
                        ^
    c-blosc/internal-complibs/zstd-1.4.1/decompress/zstd_decompress.c:93:21: error: use of undeclared identifier 'ZSTD_FRAMEHEADERSIZE_PREFIX'
                        ZSTD_FRAMEHEADERSIZE_PREFIX;
                        ^
    c-blosc/internal-complibs/zstd-1.4.1/decompress/zstd_decompress.c:94:24: error: use of undeclared identifier 'ZSTD_FRAMEHEADERSIZE_PREFIX'
        ZSTD_STATIC_ASSERT(ZSTD_FRAMEHEADERSIZE_PREFIX >= ZSTD_FRAMEIDSIZE);
                           ^
    c-blosc/internal-complibs/zstd-1.4.1/decompress/zstd_decompress.c:379:23: error: use of undeclared identifier 'ZSTD_FRAMEHEADERSIZE_PREFIX'
        while (srcSize >= ZSTD_FRAMEHEADERSIZE_PREFIX) {
                          ^
    c-blosc/internal-complibs/zstd-1.4.1/decompress/zstd_decompress.c:631:28: error: use of undeclared identifier 'ZSTD_FRAMEHEADERSIZE_MIN'
            remainingSrcSize < ZSTD_FRAMEHEADERSIZE_MIN+ZSTD_blockHeaderSize,

Environment:
macOS (0.15.6 (19G73))
Python 3.7.7

**Comment by joshmoore** [comment]
blosc is a native library for compression that zarr depends on itself. It's possible to get it installed natively, or even via brew, but for the cost of a second Python installation, I'd suggest using [conda](https://docs.conda.io/en/latest/miniconda.html) to simplify everything. Once you have conda installed:

```
conda create -n example -c conda-forge zarr
conda activate example
pip install ome-zarr
```

should get you everything you need.

**Comment by jrevote** [comment]
Thanks Josh, installation of ome-zarr via conda works now.
