### ISSUE TITLE
Change github link from PyPi package to docs

### ISSUE THREAD

**Issue by dstansby** [ome/ome-zarr-py#401]
It would be nice to change the link in the sidebar on GitHub from the PyPi link, to the docs (https://ome-zarr.readthedocs.io/en/stable/), as I imagine that's a more helpful site for users looking to use the package.

<img width="365" alt="Screenshot 2024-10-29 at 19 11 56" src="https://github.com/user-attachments/assets/278549d2-1d8e-42fb-bbce-ca46837ba7dc">

**Comment by will-moore** [comment]
Make sense to increase the visibility of the docs...
Done. Any objections @joshmoore ?

**Comment by joshmoore** [comment]
Nope. 👍🏼
