### ISSUE TITLE
Bloated dependencies and installation

### ISSUE THREAD

**Issue by constantinpape** [ome/ome-zarr-py#90]
I think that the dependencies are a bit bloated in this package.
In particular:
- opencv dependency: this should be avoided if there is also scikit-image in the dependencies; for me this makes the package unusable in many deployments because opencv clashes with other dependencies. Afaik opencv is only used for nearest neighbor downsampling, which can also be done with scikit-image.
- vispy dependency: why? there is no visualisation involved here. Probably this is a leftover from the napari cookiecutter.
- napari: same as vispy

Also, in the installation the package installs a napari plugin, which should be removed in favor of `napari-ome-zarr`.

**Comment by sbesson** [comment]
@constantinpape note there is an ongoing work on https://github.com/ome/ome-zarr-py/pull/86 as a follow-up of the extraction of the `napari` layer into its separate repository. I would assume at least the `napari` dependency can be removed straight away.

**Comment by joshmoore** [comment]
Yup, merged. Sorry, I thought I had done that last week.

@constantinpape : if you have a scikit-image implementation that can also downsample labels, then we can look into dropping.

What's the clash in the dependencies? Would pinning versions help?

**Comment by constantinpape** [comment]
> @constantinpape : if you have a scikit-image implementation that can also downsample labels, then we can look into dropping.
> 
> What's the clash in the dependencies? Would pinning versions help?

vigra and several of my own dependencies.
I don't think pinning helps much, opencv is just a massive dependency that I try to avoid at all costs because it does not play nice with other c++/python packages. (And I think it's not necessary for most use cases because the same functionality is there in scikit-image.)

**Comment by joshmoore** [comment]
I went through half-a-dozen different attempts to downsample the labels until settling on opencv. You're likely much more proficient in what's available/possible though.

**Comment by constantinpape** [comment]
> I went through half-a-dozen different attempts to downsample the labels until settling on opencv. You're likely much more proficient in what's available/possible though.

Ok, I can just include a scikit-image version in #89 and we can iterate on this in that PR.

**Comment by lassoan** [comment]
Thanks for providing this nice package! We plan adopt ome-zarr in [3D Slicer](https://www.slicer.org/) and writing an import plugin in Python using ome-zarr-py would be ideal.

However, we cannot deal with OpenCV and vispy as dependencies. They are huge and for us they are redundant (we use ITK and VTK instead). Wheels are not available in all the environments that we need to support and we cannot take on the development and support efforts needed for building wheels for such large and complex packages.

It is great to see from the discussions and pull requests that the OpenCV requirement is going away. It would be awesome if you could find a way to make vispy optional, too. Thank you.

**Comment by constantinpape** [comment]
> It would be awesome if you could find a way to make vispy optional, too. Thank you.

We have discussed this somewhere already: the vispy dependency is also not necessary; right now it is only used to create a colormap for the downstream napari plugin and it is possible to do this as a plain python type and then convert to vispy in the downstream application.

I am working on #89 this week and will follow up on the vispy dependency once that's done.

**Comment by joshmoore** [comment]
vispy removal is hopefully covered with https://github.com/ome/ome-zarr-py/pull/91 and https://github.com/ome/napari-ome-zarr/pull/10, though comments welcome.

**Comment by lassoan** [comment]
Awesome, thank you!

**Comment by constantinpape** [comment]
Once vispy is removed we should also simplfy the test env and remove all the PyQT5 / PySide2 logic.

**Comment by joshmoore** [comment]
> Edit: I just saw that #91 is doing exactly that :).

:+1: :wink:

**Comment by BioinfoTongLI** [comment]
Hello there!
I still see `vispy` being installed with `pip install ome-zarr`
```
root@74caf98b9df5:/# pip install ome-zarr
Collecting ome-zarr
  Downloading ome_zarr-0.0.20-py3-none-any.whl (24 kB)
Collecting fsspec>=0.9.0
  Downloading fsspec-2021.7.0-py3-none-any.whl (118 kB)
     |################################| 118 kB 35.4 MB/s
Collecting opencv-contrib-python-headless
  Downloading opencv_contrib_python_headless-4.5.3.56-cp36-cp36m-manylinux2014_x86_64.whl (42.3 MB)
     |################################| 42.3 MB 139 kB/s
Collecting vispy
  Downloading vispy-0.7.3.tar.gz (13.4 MB)
     |################################| 13.4 MB 85.0 MB/s
     ```
Is this expected?

**Comment by joshmoore** [comment]
Hi @BioinfoTongLI. The PR is merged but not yet released. Few more ducks to get in a row.

**Comment by joshmoore** [comment]
Latest release should be vispy-free.

**Comment by sbesson** [comment]
With `ome-zarr 0.1.0`, all three dependencies mentioned in this issue have been removed. Anything else to do here or should we close this issue @constantinpape ?

**Comment by constantinpape** [comment]
Yes, I think the dependencies look good now, so we can close this.

**Comment by lassoan** [comment]
Thanks a lot guys. This makes this package much easier to use in our projects.
